"""add_fund_snapshot_extended_fields

Revision ID: 1a6fef39b33f
Revises: 
Create Date: 2026-02-15 00:01:21.489907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6fef39b33f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_snapshot', sa.Column('cash_not_reported', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('assets_invested', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('assets_misc_sec', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('amt_pay_one_yr_banks_borr', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('amt_pay_one_yr_ctrld_comp', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('amt_pay_one_yr_oth_affil', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('amt_pay_one_yr_other', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('amt_pay_aft_one_yr_banks_borr', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('amt_pay_aft_one_yr_ctrld_comp', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('amt_pay_aft_one_yr_oth_affil', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('amt_pay_aft_one_yr_other', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('delay_deliv', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('stand_by_commit', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('liquidity_pref', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('fund_snapshot', sa.Column('is_non_cash_collateral', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_snapshot', 'is_non_cash_collateral')
    op.drop_column('fund_snapshot', 'liquidity_pref')
    op.drop_column('fund_snapshot', 'stand_by_commit')
    op.drop_column('fund_snapshot', 'delay_deliv')
    op.drop_column('fund_snapshot', 'amt_pay_aft_one_yr_other')
    op.drop_column('fund_snapshot', 'amt_pay_aft_one_yr_oth_affil')
    op.drop_column('fund_snapshot', 'amt_pay_aft_one_yr_ctrld_comp')
    op.drop_column('fund_snapshot', 'amt_pay_aft_one_yr_banks_borr')
    op.drop_column('fund_snapshot', 'amt_pay_one_yr_other')
    op.drop_column('fund_snapshot', 'amt_pay_one_yr_oth_affil')
    op.drop_column('fund_snapshot', 'amt_pay_one_yr_ctrld_comp')
    op.drop_column('fund_snapshot', 'amt_pay_one_yr_banks_borr')
    op.drop_column('fund_snapshot', 'assets_misc_sec')
    op.drop_column('fund_snapshot', 'assets_invested')
    op.drop_column('fund_snapshot', 'cash_not_reported')
    # ### end Alembic commands ###
