"""Add enhanced derivative columns for US-5

Revision ID: 832998c69d8b
Revises: 1a6fef39b33f
Create Date: 2026-02-15 00:43:00.321166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832998c69d8b'
down_revision: Union[str, None] = '1a6fef39b33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('derivative', sa.Column('currency_sold', sa.String(length=3), nullable=True))
    op.add_column('derivative', sa.Column('currency_amt_sold', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('derivative', sa.Column('settlement_date', sa.Date(), nullable=True))
    op.add_column('derivative', sa.Column('written_notional_amt', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('derivative', sa.Column('other_amt', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('holding', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('holding', sa.Column('payoff_profile', sa.String(length=10), nullable=True))
    op.add_column('holding', sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('holding', sa.Column('holding_key', sa.String(length=500), nullable=False))
    op.drop_constraint(op.f('holding_uniq'), 'holding', type_='unique')
    op.create_unique_constraint('holding_uniq', 'holding', ['etf_id', 'report_date', 'holding_key', 'filing_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('holding_uniq', 'holding', type_='unique')
    op.create_unique_constraint(op.f('holding_uniq'), 'holding', ['etf_id', 'report_date', 'cusip', 'filing_date'])
    op.drop_column('holding', 'holding_key')
    op.drop_column('holding', 'exchange_rate')
    op.drop_column('holding', 'payoff_profile')
    op.drop_column('holding', 'title')
    op.drop_column('derivative', 'other_amt')
    op.drop_column('derivative', 'written_notional_amt')
    op.drop_column('derivative', 'settlement_date')
    op.drop_column('derivative', 'currency_amt_sold')
    op.drop_column('derivative', 'currency_sold')
    # ### end Alembic commands ###
